### ISSUE TITLE
About the datasets of dogs and cars? 

### ISSUE THREAD

**Issue by cy-coding** [leesb7426/CVPR2022-Task-Discrepancy-Maximization-for-Fine-grained-Few-Shot-Classification#6]
This is a great work. According to the readme file you provided, I found that there is no data set division process and files for cars and dogs. Could you please provide your divided data set? Or can you provide the division files and usage tutorials? Thank you very much

**Comment by leesb7426** [comment]
Thank you for your interest in our paper, and we apologize for the delayed response due to personal circumstances.

As mentioned in our paper, the splits used in our work follow those in "Revisiting Local Descriptor-Based Image-to-Class Measure for Few-Shot Learning."

Additionally, the performance reported in our paper is based on non-optimized parameters. 
This decision was made because, due to the modular nature of our method, the time overhead for optimizing parameters across all baseline methods was extremely high.

We recommend referring to the GitHub repository of the paper "Bi-directional Feature Reconstruction Network for Fine-Grained Few-Shot Image Classification," which reproduced our method, for parameter settings.

Lastly, please note that the performance of our method is reported differently between the AAAI and Arxiv versions of the aforementioned paper. 
This discrepancy occurred because we initially provided a GitHub implementation that omitted a noise option to prevent overfitting.

Thank you again for your interest in our work. Please feel free to reach out if you have any further questions.
